version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
  template-service:
    image: localhost:5000/template-service:latest
    container_name: template-service
    environment:
      - MONGODB_URI=mongodb://mongodb/test
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
volumes:
  mongodb-data:
